### PR TITLE
Start using pip-compile

### PR DESCRIPTION
**Pull request by breerly**
http://nvie.com/posts/better-package-management/

### CODE REVIEW

**Comment by breerly** [comment]
I can't get `pip-sync` working, created https://github.com/nvie/pip-tools/issues/340

**Comment by blampe** [comment]
As part of the testing step you'll need to do something like `python setup.py develop` to re-install the package locally -- `pip-sync` removes `yarpc` from the environment.

**Comment by blampe** [comment]
You'll need to do a similar `sed` line to not install some c packages when building for pypy.

**Comment by abhinav** [comment]
LGTM

**Pull request merged**
