### PR TITLE
Rename RPC.listen to RPC.start to match other impls

### LINKED ISSUE #8: Rename listen to start

### PR DESCRIPTION
**Pull request by breerly**
Fixes #8 

cc @kriskowal @abhinav @junchaowu

### CODE REVIEW

**Comment by breerly** [comment]
Do we also want to rename our Inbound's listen/serve function to `start`?

**Comment by kriskowal** [comment]
I did.

**Comment by kriskowal** [comment]
:ok:

**Comment by breerly** [comment]
Ok - I've renamed `listen/serve` all the way down to the transport layer.

Please make sure you do the same.

**Pull request merged**
